---
fixtures:
  repositories:
    stdlib:
      ref: "v6.6.0"
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
    apt:
      ref: "v7.7.1"
      repo: "https://github.com/puppetlabs/puppetlabs-apt"
  symlinks:
    vision_hashicorp: '#{source_dir}'
